version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: parkfinderMqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  redis:
    image: redis:alpine
    container_name: parkfinderRedis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}"
    restart: always
    environment:
     - REDIS_PASSWORD=${REDIS_PASSWORD}

  app:
    build: .
    container_name: parkfinderRealtime
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    environment:
      - PORT=${PORT}
      - MQTT_HOST=mqtt
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - NODE_ENV=production
    depends_on:
      - mqtt
      - redis